# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'SpendManagerSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpendManagerSample
  pod 'Sensibill', :git => 'git@github.com:getsensibill/sdk-ios.git', :tag => 'v2025.0.0'

  target 'SpendManagerSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpendManagerSampleUITests' do
    # Pods for testing
  end

end
